---
title: "diff_peaks_test"
output: html_notebook
---


## ** First I want to get into the correct dir from when i launch the eureka Rstudio ** 
```{r}

# do not need this part if you are using this script in nextflow or using files from your own dir
# only used if eureka starts you off at your username dir
current_dir = getwd()

peak_project_dir = paste0(current_dir, "/pipelines/peak_calling_analysis_pipeline")

```

## Load libraries

```{r}
library(DESeq2)
library(tidyr)
```


### now to get the list of peak files from H3k27me3

```{r}
# this will allow me to list all of the files in the directories

k27me3_peak_list = list.files(path="./peak_files/", pattern="*H3k27me3*", recursive = TRUE, full.names = TRUE)

# now to create a for loop that will read all of the files and put them into a grange object

# these will be the master peaks

mPeak = GRanges()

for (file in k27me3_peak_list) {
  
  
  #file_path = paste0("./peak_files", file)
  peakRes = read.table(file, header = FALSE, fill = TRUE )
  
  # the peak files generated by macs2 will have the first row as description stuff, so I needed to remove it
  # so IRanges can have the start and stop as numeric. Which I also modified from the tutorial I looked at
  peakRes = peakRes[-1,]
  
  # modified this to makesure the start and stop are seen as numeric.
  mPeak = GRanges( seqnames = peakRes$V1, IRanges(start = as.numeric(peakRes$V2), end = as.numeric(peakRes$V3)), strand = "*") %>% append(mPeak, .)
}
j
masterPeak = reduce(mPeak)
```


